// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Seed runner is TypeScript and executed directly by Node:
    // - --experimental-strip-types: execute .ts files without precompiling.
    // - --experimental-specifier-resolution=node: resolve seed module imports
    //   predictably in this ESM/CJS mixed project setup.
    seed: 'node --experimental-strip-types --experimental-specifier-resolution=node prisma/seed/main.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
