export {
  AdminLoginApi,
  ConfirmEmailApi,
  ForgotPasswordApi,
  ForceChangePasswordApi,
  LoginApi,
  LogoutApi,
  MeApi,
  RefreshApi,
  RegisterApi,
  RegisterViaInviteApi,
  ResetPasswordApi,
  ResendConfirmationEmailApi,
  RegisterCompanyOwnerApi,
} from './auth-api-docs.decorators';
