import {
  Controller,
  Get,
  HttpCode,
  HttpStatus,
  Query,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiOkResponse,
  ApiQuery,
  ApiTags,
} from '@nestjs/swagger';
import { AppService } from './app.service';
import { JwtAuthGuard } from './auth/guards/jwt-auth.guard';
import { PDF_JOBS, PDF_TEMPLATES, QueueService } from './infrastructure/queue';

@ApiTags('Demo')
@Controller()
export class AppController {
  constructor(
    private readonly appService: AppService,
    private readonly queueService: QueueService,
  ) {}

  @Get()
  getHello(): string {
    return this.appService.getHello();
  }

  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth('access-token')
  @ApiOkResponse({
    description: 'Enqueued demo PDF generation job.',
    schema: {
      type: 'object',
      properties: {
        message: { type: 'string' },
        jobId: { oneOf: [{ type: 'string' }, { type: 'number' }] },
      },
    },
  })
  @ApiQuery({
    name: 'title',
    required: false,
    type: String,
    description: 'Optional title rendered in demo PDF.',
  })
  @Get('demo/pdf')
  @HttpCode(HttpStatus.OK)
  async enqueueDemoPdf(
    @Query('title') title = 'NTI PDF Queue Demo',
  ): Promise<{ message: string; jobId: string | number | undefined }> {
    const generatedAt = new Date().toISOString();

    const html = `
      <html>
        <head>
          <meta charset="utf-8" />
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #1f2937; }
            h1 { margin: 0 0 16px; font-size: 24px; }
            p { margin: 0 0 12px; font-size: 14px; }
            code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <p>This PDF was generated by the background worker from a BullMQ job.</p>
          <p>Generated at: <code>${generatedAt}</code></p>
        </body>
      </html>
    `;

    const job = await this.queueService.addPdf(PDF_JOBS.RENDER_TEMPLATE, {
      template: PDF_TEMPLATES.REPORT,
      data: { html },
    });

    return {
      message: 'PDF job enqueued',
      jobId: job.id,
    };
  }
}
